name: Create blog links
on: workflow_dispatch
jobs:
  fetch-and-create:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install -y libxml-compile-perl libjson-xs-perl
      - uses: actions/checkout@v2
      - run: |
          curl https://default.cf/blog/feed.xml \
            | sed -e 's/xmlns=/xmlns:atom=/' \
            | xml2json -x - -s feed.xsd \
            > _data/feed.json
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Update feed.json'
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
